name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    uses: gymia-fit/.github/.github/workflows/ci-node.yml@main
    with:
      working-directory: fitnexa-business-landing
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
